### ISSUE TITLE
Prodnote can cause aside inside p

### ISSUE THREAD

**Issue by egli** [sbsdev/pipeline#7]
Especially if you use an inline `prodnote`. So the generated HTML is not valid. Need to talk to Jostein and possibly fix it in the migrator

**Comment by egli** [comment]
Hm, the code indicates that prodnotes are converted to `section` (if inside the jacket or cover) or `aside` otherwise. @mixa72 could you describe the problem again?

**Comment by mixa72** [comment]
The migrator converts the prodnote element in the following dtbook snippet 
````
<p>... siehe Kreuzworträtsel links <prodnote render="required">nicht übertragen</prodnote>.</p>
````
to an aside element in EPUB3:
````
<p>... siehe Kreuzwortr&#xe4;tsel links <aside id="prodnote_1" class="prodnote render-required" epub:type="z3998:production">nicht &#xfc;bertragen</aside>.</p>
````
In accordance with the guidelines on https://developer.mozilla.org/en-US/docs/Web/HTML/Element/aside, p is a permitted parent of aside.  Validation with oXygen, however, results in an error "aside not allowed here". Is oXygen's validator too strict or is aside not allowed inside p?

**Comment by egli** [comment]
Aha, so this might actually be more of a problem of oXygen? @mixa72 What does epubcheck say?

**Comment by mixa72** [comment]
Epubcheck gives the same result:
````
Error while parsing file 'element "aside" not allowed here; expected the element end-tag, text or element "a", "abbr", "area", "audio", "b", "bdi", "bdo", "br", "button", "canvas", "cite", "code", "command", "datalist", "del", "dfn", "em", "embed", "epub:switch", "i", "iframe", "img", "input", "ins", "kbd", "keygen", "label", "link", "map", "mark", "meta", "meter", "ns1:math", "ns2:svg", "object", "output", "progress", "q", "ruby", "s", "samp", "script", "select", "small", "span", "strong", "sub", "sup", "textarea", "time", "u", "var", "video" or "wbr" (with xmlns:ns1="http://www.w3.org/1998/Math/MathML" xmlns:ns2="http://www.w3.org/2000/svg")'.
````
So, it appears that `aside` inside `p` is indeed not allowed.

**Comment by egli** [comment]
So what this probably boils down to is to have a specialized matcher for inline prodnotes, i.e. prodnotes inside block elements that just emits an inline element such as `span` instead of an `aside`

**Comment by egli** [comment]
PR (nlbdev/nordic-epub3-dtbook-migrator#367) has been approved but not merged yet
